### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tpmccallum** [phated/grain-advent-of-code#3]
Hi,
This is cool :)

I get an error `RangeError: Maximum call stack size exceeded` when running the 01-01-2020 problem 1 example.

I set `ulimit -s 85000` which is the max and then learned that I had to reduce the amount of numbers in the `data` list to get rid og this error. 

Any thoughts?

Tim

**Comment by phated** [comment]
It's not related to a ulimit, it's related to recursion. The file specifies `/* grainc-flags --experimental-wasm-tail-call */`, did you remove that? Are you trying to run on a platform that doesn't support tail calls?

**Comment by tpmccallum** [comment]
Hi, 
Ah, yes, I did remove that line for some testing on another platform.
Thanks so much!
Tim
